### ISSUE TITLE
Display Druid Query option not working as expected

### ISSUE THREAD

**Issue by a2l007** [allegro/turnilo#418] opened 2019-05-08 20:38 UTC
Attempting to access the "Display Druid Query" option lands in a blank page. I can see the following error in the logs:
```
Client Error: {"message":"Error: must filter on time unless the allowEternity flag is set","file":"http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js","line":1,"column":344988,"stack":"gt</e.prototype.timeFilterToIntervals@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:344988\ngt</e.prototype.filterToDruid@http://proudshroud.corp.gq1.yahoo.com:4443/app.7e094fdf734a95564ed7.js:1:344728\nIt</n.prototype.getQueryAndPostTransform@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:383805\nht</e.prototype.simulateValue@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:327279\nJe</e.prototype._computeResolvedSimulate/</<@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:220147\nn.fillDatasetExternalAlterations@http://proudshroud.corp.gq1.yahoo.com:4443/app.7e094fdf734a95564ed7.js:1:183113\nn.fillExpressionExternalAlteration@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:182817\nJe</e.prototype._computeResolvedSimulate/<@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:220112\nJe</e.prototype._computeResolvedSimulate@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:220092\nJe</e.prototype.simulateQueryPlan@http://proudshroud.corp.gq1.com:4443/app.7e094fdf734a95564ed7.js:1:219794\nn.DruidQueryModal@http://proudshroud.corp.gq1.yahoo.com:4443/app.7e094fdf734a95564ed7.js:37:1476617\nbeginWork@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:31711\nr@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:44327\na@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:44648\ns@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:44886\nw@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:48429\nS@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:48166\nbatchedUpdates@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:49595\nZ@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:9667\nke@http://proudshroud.corp.gq1.com:4443/main.js?v=1.14.0:14:14119\n","hash":"#Metrics_Cluster_V2/4/N4IgbglgzgrghgGwgLzgFwgewHYgFwhLYCmAtAMYAWcATmiADQgYC2xyOx+IAomuQHoAqgBUAwoxAAzCAjTEaUfAG1QaAJ4AHLgVZcmNYlO57JegAoKsAEyV5VIazBrosuAuZEBGABKSo8pr4pF5MGtrcCOjEASAAvgC6iUxQmkhodg7hOswQbJLWecTYUG4mRZIA5i7YMFE0EBrcnl4Asv6YdPig2g2Y1txmWjmFbCVlTIWG5Bg43HBQ5MWF2JWShsa6FXFMSCyN+LUICMkgUFYxKqAbCsVL3OSYMNj0TFKdLOjdzMPc1kZwOqvcCIGA5eI7a5GW7Ye4EYhgYoZSTvGifeh4NS/Aj/KSAuSSMCg8FxSEgG6GWE5fa4N4fL6Yn4RHEAoGE4mDUkMKFSGFwkCfAAeKPpGKxzMcrIJTCJCDBnNOmgg2BI1gAIkVxjhMiAAPrkOUBBT+BSQe5MNhoBrkSSUTCxBJMJUq4jWADKnQxIARSKUu2IlWWhzqCCYlAglUoSEjGKOJyAA"}
```

**Comment by adrianmroz** [comment] 2019-05-08 21:02
What version?

Do you have filter on time dimension?

Does query works (i.e. visualisation loads as expected), but just modal breaks?

**Comment by a2l007** [comment] 2019-05-08 21:06
I'm on 1.14.0. I do have a time dimension filter. It loads into a blank page which means query is not working. Also once I'm in the blank page, the back button wouldn't take me back to the previous page.

**Comment by adrianmroz** [comment] 2019-05-08 21:10
But before clicking „Display Druid Query”, visualisation loads? If so, can you paste view definition?

**Comment by a2l007** [comment] 2019-05-08 21:13
Yes it does. Following is the view definition:
```
{
  "dataCubeName": "Metrics_Cluster_V2",
  "viewDefinitionVersion": "4",
  "viewDefinition": {
    "visualization": "line-chart",
    "timezone": "Etc/UTC",
    "filters": [
      {
        "type": "time",
        "ref": "time",
        "timePeriods": [
          {
            "duration": "PT1H",
            "step": -1,
            "type": "latest"
          }
        ]
      }
    ],
    "splits": [
      {
        "type": "time",
        "dimension": "time",
        "granularity": "PT1M",
        "sort": {
          "period": "",
          "type": "dimension",
          "direction": "ascending",
          "ref": "time"
        },
        "limit": null
      }
    ],
    "series": [
      {
        "reference": "count",
        "format": {
          "type": "default",
          "value": ""
        }
      },
      {
        "reference": "events",
        "format": {
          "type": "default",
          "value": ""
        }
      },
      {
        "reference": "min",
        "format": {
          "type": "default",
          "value": ""
        }
      }
    ],
    "pinnedDimensions": [
      "_cluster",
      "service",
      "metric",
      "host"
    ],
    "pinnedSort": "events",
    "legend": null,
    "highlight": null
  }
}
```

**Comment by adrianmroz** [comment] 2019-05-08 21:23
And I assume in config you have defined `timeAttribute: time`? Or you run without config? If not, maybe introspection can’t infer timeAttribute. Nevertheles, I will try reproduce issue.

**Comment by a2l007** [comment] 2019-05-09 00:42
Yeah I have `timeAttribute: time` set in my config.yaml. Are you able to see Druid queries on your end? I'm trying to figure out if it is a config issue on my side.

**Comment by adrianmroz** [comment] 2019-05-09 09:50
Yes, Druid queries modal works in our configuration on 1.14. My only suspicion is that when creating simulated external (https://github.com/allegro/turnilo/blob/master/src/client/modals/druid-query-modal/druid-query-modal.tsx#L34) we somewhat lose knowledge about time dimension.

**Comment by adrianmroz** [comment] 2019-05-09 10:05
Ok, I can't reproduce that on my end, but if you feel courageous, can you paste me there your plywood expression for this view? It is visible in Network tab in DevTools in Request Payload for `plywood` endpoint. If you have pinboard open, there will be two requests, you can paste both, I will figure out which is which. 

Error you showed is thrown when filter expression is just `LiteralExpression` from `plywood`. It shouldn't be according to your ViewDefinition but who knows, maybe you hit some edge case ...

**Comment by a2l007** [comment] 2019-05-09 22:00
Clicking on Display Druid Query generates only one request and this request does not seem to have an plywood expression header. Maybe I'm looking at the wrong place?
I'll try to investigate this further today

**Comment by alexbusu** [comment] 2019-05-17 08:13
Maybe it's related. https://github.com/allegro/turnilo/pull/394 . Should be fixed in v1.15. Btw, @adrianmroz when is the release? :)

**Comment by adrianmroz** [comment] 2019-05-17 08:17
Soon ...

On serious note, we're running beta in our company and it's looking promising, so I would say next week.

**Comment by alexbusu** [comment] 2019-06-13 08:20
@a2l007 did the issue gone using version `^1.15`?

**Comment by adrianmroz** [comment] 2020-01-02 11:04
Close due to inactivity.

**Closed by adrianmroz** 2020-01-02 11:04 UTC
