### ISSUE TITLE
CSS issues in Chrome and Firefox

### ISSUE THREAD

**Issue by l2dy** [allegro/turnilo#443] opened 2019-06-11 03:38 UTC
#### Chrome 75.0.3770.80
<img width="231" alt="Chrome1" src="https://user-images.githubusercontent.com/14329097/59242146-fed4fe80-8bf9-11e9-9125-f9c7c519e4e2.png">
<img width="334" alt="Chrome2" src="https://user-images.githubusercontent.com/14329097/59242151-0399b280-8bfa-11e9-8ef8-7feaeeeb23a8.png">

#### Firefox 67.0.1
<img width="231" alt="Firefox1" src="https://user-images.githubusercontent.com/14329097/59242158-0d231a80-8bfa-11e9-9c81-fa6ec82f4357.png">
<img width="351" alt="Firefox2" src="https://user-images.githubusercontent.com/14329097/59242165-10b6a180-8bfa-11e9-90fb-cb125bc9f26a.png">

**Comment by l2dy** [comment] 2019-06-11 03:39
Screenshots captured from aa0bfcb8ab5d59366dbfd0b95ddc32a8f192a901.

**Comment by adrianmroz** [comment] 2019-06-12 10:10
Firefox issue resolved in #444, can't reproduce Chrome bug so will appreciate PR :)

**Comment by l2dy** [comment] 2019-06-12 10:54
FYI, the Chrome bug was reproduced on macOS 10.14 *with a USB mouse plugged in*.

**Comment by l2dy** [comment] 2019-06-20 07:21
Height of the measure-item div changed from 27px to 24px. I think this is how the scroll bar appeared in Chrome.

1.14.0 (good):

<img width="313" alt="good" src="https://user-images.githubusercontent.com/14329097/59828950-adc8b700-932b-11e9-98c9-87745e28b521.png">

05e699041b14cd4c7148b8a4b61523848a3cd0b1 (bad):

<img width="314" alt="t-bad" src="https://user-images.githubusercontent.com/14329097/59828971-bc16d300-932b-11e9-87bb-28fd3b189902.png">

**Closed** 2019-08-05 11:47 UTC
Labels: help wanted
