### ISSUE TITLE
CVS download does not work on "totals" view

### ISSUE THREAD

**Issue by nuria** [allegro/turnilo#197] opened 2018-10-11 21:50 UTC
To repro:

1) open turnilo
2) try to open CVS download option when in "total" mode
3) option does not appear as available

Please also see following ticket for context: https://phabricator.wikimedia.org/T206760

**Comment by adrianmroz** [comment] 2018-10-12 08:37
Hi,

What version of turnilo do you use? I checked it right now on 1.8.1 and couldn't reproduce on my data and on example data.

**Comment by nuria** [comment] 2018-10-15 17:56
Let us update to latest and see if this issue is still present, thanks for the fast response. Will update ticket.

**Comment by mkuthan** [comment] 2018-12-12 08:21
@nuria - could you confirm that the current Turnilo version is not affected by this bug?
Thanks!

**Comment by adrianmroz** [comment] 2018-12-12 08:57
@mkuthan I think we can close this issue considering: https://phabricator.wikimedia.org/T206760

**Comment by nuria** [comment] 2018-12-12 16:00
Confirming, many thanks

**Closed** 2018-12-18 12:40 UTC
Labels: bug
