### ISSUE TITLE
[Breaking] Error in time shift line charting and tables

### ISSUE THREAD

**Issue by ravibhushankumarsonu** [allegro/turnilo#542] opened 2019-12-16 06:26 UTC
Turnilo isn't working acceptably on time shift functionality. While doing the time split with time shift. The table is demonstrating the same value for the present and earlier day data. Which is likewise in case of charting.
![Screenshot 2019-12-16 at 11 28 12 AM](https://user-images.githubusercontent.com/13804540/70883898-667d6380-1ffa-11ea-9c58-ea05204a589e.jpg)
If we see the data for 5th Dec. Data on the current and previous day both are 3184 units with day time shifts. But according to functionality the data for the previous day should be 2762 units.
The same problem is with the line chart too. 
<img width="942" alt="Screenshot 2019-12-16 at 11 30 08 AM" src="https://user-images.githubusercontent.com/13804540/70884066-d8ee4380-1ffa-11ea-832b-5a4b99f37aad.png">

**Comment by l2dy** [comment] 2019-12-16 06:50
Duplicate of #449?

**Comment by adrianmroz** [comment] 2019-12-16 15:04
Yeah, it is duplicate. Sadly it is impossible to fix. Let’s track alternative solution in #449

**Closed by adrianmroz** 2019-12-16 15:04 UTC
